-- WABOS core schema (Postgres). Final shape after Phases A–C. ids use
-- GENERATED BY DEFAULT AS IDENTITY so the sqlite→pg copy can preserve ids and we
-- can seed business 1. Timestamps are epoch bigints (as in SQLite). Money/REAL
-- columns are double precision. Booleans are kept as integer 0/1 to match code.

CREATE TABLE IF NOT EXISTS businesses (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text   NOT NULL DEFAULT '',
  wa_phone   text,
  plan_tier  text   NOT NULL DEFAULT 'free',
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS settings (
  business_id bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  key         text   NOT NULL,
  value       text   NOT NULL,
  PRIMARY KEY (business_id, key)
);

CREATE TABLE IF NOT EXISTS contacts (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  jid        text NOT NULL,
  phone      text NOT NULL,
  name       text NOT NULL DEFAULT '',
  notes      text NOT NULL DEFAULT '',
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  UNIQUE (business_id, jid)
);

CREATE TABLE IF NOT EXISTS tags (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  name        text NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tags_business_name ON tags (business_id, lower(name));

CREATE TABLE IF NOT EXISTS contact_tags (
  contact_id bigint NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  tag_id     bigint NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (contact_id, tag_id)
);

CREATE TABLE IF NOT EXISTS conversations (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id     bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  contact_id      bigint NOT NULL UNIQUE REFERENCES contacts(id) ON DELETE CASCADE,
  mode            text NOT NULL DEFAULT 'ai' CHECK (mode IN ('ai','human')),
  unread_count    integer NOT NULL DEFAULT 0,
  last_message_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  agent_id        bigint
);

CREATE TABLE IF NOT EXISTS messages (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wa_message_id   text,
  conversation_id bigint NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  direction       text NOT NULL CHECK (direction IN ('in','out')),
  type            text NOT NULL DEFAULT 'text',
  text            text NOT NULL DEFAULT '',
  from_ai         integer NOT NULL DEFAULT 0,
  status          text NOT NULL DEFAULT 'sent',
  timestamp       bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_wa_id ON messages(wa_message_id) WHERE wa_message_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, timestamp);

CREATE TABLE IF NOT EXISTS products (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  name        text NOT NULL,
  description text NOT NULL DEFAULT '',
  price       double precision NOT NULL DEFAULT 0,
  currency    text NOT NULL DEFAULT 'PEN',
  active      integer NOT NULL DEFAULT 1,
  created_at  bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS faqs (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  question    text NOT NULL,
  answer      text NOT NULL
);

CREATE TABLE IF NOT EXISTS agents (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id           bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  name                  text NOT NULL,
  slug                  text NOT NULL,
  description           text NOT NULL DEFAULT '',
  persona               text NOT NULL DEFAULT '',
  ai_tone               text NOT NULL DEFAULT '',
  ai_instructions       text NOT NULL DEFAULT '',
  communication_profile text,
  model_default         text NOT NULL DEFAULT '',
  model_sales           text NOT NULL DEFAULT '',
  is_default            integer NOT NULL DEFAULT 0,
  enabled               integer NOT NULL DEFAULT 1,
  created_at            bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_agents_slug ON agents(business_id, slug);

CREATE TABLE IF NOT EXISTS knowledge_collections (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  name        text NOT NULL,
  description text NOT NULL DEFAULT '',
  sort_order  integer NOT NULL DEFAULT 0,
  created_at  bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS knowledge_documents (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id   bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  collection_id bigint REFERENCES knowledge_collections(id) ON DELETE SET NULL,
  title         text NOT NULL,
  kind          text NOT NULL DEFAULT 'other' CHECK (kind IN ('policy','guide','brand','faq','other')),
  summary       text NOT NULL DEFAULT '',
  content       text NOT NULL DEFAULT '',
  keywords      text NOT NULL DEFAULT '',
  pinned        integer NOT NULL DEFAULT 0,
  active        integer NOT NULL DEFAULT 1,
  created_at    bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  updated_at    bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE INDEX IF NOT EXISTS idx_knowledge_docs_business ON knowledge_documents(business_id, active);

CREATE TABLE IF NOT EXISTS broadcasts (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  name        text NOT NULL,
  message     text NOT NULL,
  tag_id      bigint REFERENCES tags(id) ON DELETE SET NULL,
  status      text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sending','done','failed')),
  total       integer NOT NULL DEFAULT 0,
  sent        integer NOT NULL DEFAULT 0,
  failed      integer NOT NULL DEFAULT 0,
  created_at  bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS broadcast_recipients (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broadcast_id bigint NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
  contact_id   bigint NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  status       text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','failed')),
  error        text
);

CREATE TABLE IF NOT EXISTS media (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  mime       text NOT NULL,
  path       text NOT NULL,
  size_bytes bigint NOT NULL,
  sha256     text NOT NULL,
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS charges (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  contact_id  bigint NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  amount      double precision NOT NULL,
  currency    text NOT NULL DEFAULT 'PEN',
  concept     text NOT NULL DEFAULT '',
  status      text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','paid','review','rejected','expired','cancelled')),
  created_by  text NOT NULL DEFAULT 'dashboard',
  due_at      bigint,
  paid_at     bigint,
  receipt_id  bigint,
  created_at  bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE INDEX IF NOT EXISTS idx_charges_contact ON charges(contact_id, status);

CREATE TABLE IF NOT EXISTS receipts (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id            bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  media_id               bigint NOT NULL REFERENCES media(id),
  message_id             bigint NOT NULL,
  contact_id             bigint NOT NULL,
  conversation_id        bigint NOT NULL,
  charge_id              bigint REFERENCES charges(id),
  is_receipt             integer,
  provider               text,
  amount                 double precision,
  currency               text,
  date                   text,
  operation_number       text,
  sender_name            text,
  recipient_name         text,
  recipient_phone_suffix text,
  confidence             double precision,
  outcome                text NOT NULL DEFAULT 'pending'
    CHECK (outcome IN ('pending','auto_verified','review','rejected','not_receipt','manual_verified','manual_rejected')),
  reasons                text NOT NULL DEFAULT '[]',
  raw_extraction         text,
  notification_id        bigint,
  verification_method    text,
  created_at             bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_receipts_opnum ON receipts(provider, operation_number)
  WHERE operation_number IS NOT NULL AND outcome IN ('auto_verified','manual_verified');
CREATE INDEX IF NOT EXISTS idx_receipts_outcome ON receipts(outcome);

CREATE TABLE IF NOT EXISTS jobs (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id  bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  type         text NOT NULL,
  payload      text NOT NULL DEFAULT '{}',
  status       text NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued','running','done','failed','dead')),
  attempts     integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 3,
  run_at       bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  last_error   text,
  created_at   bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  updated_at   bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE INDEX IF NOT EXISTS idx_jobs_poll ON jobs(status, run_at);

CREATE TABLE IF NOT EXISTS payment_notifications (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id            bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  source                 text NOT NULL DEFAULT 'webhook' CHECK (source IN ('email','webhook','manual')),
  provider               text,
  amount                 double precision,
  currency               text NOT NULL DEFAULT 'PEN',
  operation_number       text,
  sender_name            text,
  raw_text               text,
  received_at            bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  ingested_at            bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  consumed_by_receipt_id bigint,
  external_id            text NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_paynotif_external ON payment_notifications(source, external_id);
CREATE INDEX IF NOT EXISTS idx_paynotif_opnum ON payment_notifications(provider, operation_number);
CREATE INDEX IF NOT EXISTS idx_paynotif_amount ON payment_notifications(amount, received_at);

CREATE TABLE IF NOT EXISTS style_analyses (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id            bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  status                 text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','done','failed')),
  conversations_total    integer NOT NULL DEFAULT 0,
  conversations_done     integer NOT NULL DEFAULT 0,
  messages_analyzed      integer NOT NULL DEFAULT 0,
  contacts_tagged        integer NOT NULL DEFAULT 0,
  source                 text NOT NULL DEFAULT 'human' CHECK (source IN ('human','all')),
  profile                text,
  suggested_tone         text,
  suggested_instructions text,
  model                  text,
  error                  text,
  applied_at             bigint,
  created_at             bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  completed_at           bigint
);

CREATE TABLE IF NOT EXISTS history_imports (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id       bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  status            text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','done','failed','stopped')),
  source            text NOT NULL DEFAULT 'on_demand' CHECK (source IN ('on_demand','sync')),
  messages_imported integer NOT NULL DEFAULT 0,
  chats_seen        integer NOT NULL DEFAULT 0,
  progress          integer NOT NULL DEFAULT 0,
  error             text,
  created_at        bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  updated_at        bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  completed_at      bigint
);

-- The single existing tenant (STAND 120 in production). Explicit id=1.
INSERT INTO businesses (id, name) VALUES (1, '') ON CONFLICT DO NOTHING;
-- Advance the identity sequence past the explicit id so auto-generated business
-- ids (registrations) don't collide with business 1.
SELECT setval(pg_get_serial_sequence('businesses', 'id'), (SELECT MAX(id) FROM businesses));
