-- Built-in auth (D2). Users own businesses through memberships; v1 issues one
-- owner membership per user, but the join keeps teams/multi-business a later UI
-- change rather than a schema one.

CREATE TABLE IF NOT EXISTS users (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         text NOT NULL,
  password_hash text NOT NULL,
  created_at    bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (lower(email));

CREATE TABLE IF NOT EXISTS memberships (
  user_id     bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  business_id bigint NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  role        text NOT NULL DEFAULT 'owner',
  created_at  bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  PRIMARY KEY (user_id, business_id)
);
CREATE INDEX IF NOT EXISTS idx_memberships_business ON memberships (business_id);
