-- Password recovery. A reset request stores the SHA-256 of a single-use token
-- (the raw token is emailed, never stored) with a short expiry. Consuming it
-- sets used_at so it can't be replayed.

CREATE TABLE IF NOT EXISTS password_resets (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash text   NOT NULL,
  expires_at bigint NOT NULL,
  used_at    bigint,
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE INDEX IF NOT EXISTS idx_password_resets_token ON password_resets (token_hash);
