-- Analytics event stream. A thin, append-only log of business-meaningful events
-- so dashboards can be built later without back-filling. Cheap inserts; queried
-- by (business_id, type, created_at).
CREATE TABLE IF NOT EXISTS events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  type        text NOT NULL,
  contact_id  bigint,
  amount      double precision,
  meta        jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(business_id, type, created_at);
