-- Web Push subscriptions. Each owner's browser/device that opts into
-- notifications stores its push endpoint here, scoped to the business.
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL DEFAULT 1 REFERENCES businesses(id) ON DELETE CASCADE,
  endpoint    text NOT NULL UNIQUE,
  p256dh      text NOT NULL,
  auth        text NOT NULL,
  created_at  bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE INDEX IF NOT EXISTS idx_push_business ON push_subscriptions(business_id);
