-- Native push device tokens (Capacitor iOS/Android). Separate from the browser
-- web-push subscriptions (push_subscriptions): these are FCM/APNs registration
-- tokens delivered through Firebase Cloud Messaging.
CREATE TABLE IF NOT EXISTS device_tokens (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL DEFAULT 1 REFERENCES businesses(id) ON DELETE CASCADE,
  platform    text NOT NULL CHECK (platform IN ('ios','android')),
  token       text NOT NULL UNIQUE,
  created_at  bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE INDEX IF NOT EXISTS idx_device_tokens_business ON device_tokens(business_id);
