-- Register + cash ledger: a general commerce layer under the WhatsApp AR layer.
-- Records every sale (in-store POS, WhatsApp, AI) and every non-sale cash movement
-- (expenses, extra income) so a business gets a truthful daily close and margins.
-- Ad-hoc line items (product_id NULL) let service businesses use it with no stock.

-- Per-product cost (COGS/margin) and an optional SKU for fast POS lookup.
ALTER TABLE products ADD COLUMN IF NOT EXISTS cost double precision;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sku  text;

-- A completed sale / order. Money columns are double precision (as elsewhere).
-- net = total - fee_amount. charge_id links the sale auto-created when a WhatsApp
-- charge is marked paid, so revenue has a single source of truth.
CREATE TABLE IF NOT EXISTS sales (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id    bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  contact_id     bigint REFERENCES contacts(id) ON DELETE SET NULL,
  channel        text NOT NULL DEFAULT 'pos' CHECK (channel IN ('pos','whatsapp','ai')),
  status         text NOT NULL DEFAULT 'completed' CHECK (status IN ('completed','void')),
  subtotal       double precision NOT NULL DEFAULT 0,
  discount       double precision NOT NULL DEFAULT 0,
  total          double precision NOT NULL DEFAULT 0,
  cost_total     double precision NOT NULL DEFAULT 0,
  payment_method text NOT NULL DEFAULT 'cash',
  fee_pct        double precision NOT NULL DEFAULT 0,
  fee_amount     double precision NOT NULL DEFAULT 0,
  net            double precision NOT NULL DEFAULT 0,
  currency       text NOT NULL DEFAULT 'PEN',
  note           text NOT NULL DEFAULT '',
  charge_id      bigint REFERENCES charges(id),
  created_by     text NOT NULL DEFAULT 'dashboard',
  sold_at        bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  created_at     bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE INDEX IF NOT EXISTS idx_sales_business_day ON sales(business_id, sold_at);
-- One sale per paid charge: guards the unify path against a double-insert on re-verify.
CREATE UNIQUE INDEX IF NOT EXISTS idx_sales_charge ON sales(charge_id) WHERE charge_id IS NOT NULL;

-- Sale line items. product_id NULL = ad-hoc line (service, custom item). name/
-- unit_cost are snapshots so history is stable even if the product later changes.
CREATE TABLE IF NOT EXISTS sale_items (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id    bigint NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  product_id bigint REFERENCES products(id) ON DELETE SET NULL,
  name       text NOT NULL,
  qty        double precision NOT NULL DEFAULT 1,
  unit_price double precision NOT NULL DEFAULT 0,
  unit_cost  double precision NOT NULL DEFAULT 0,
  line_total double precision NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_product ON sale_items(product_id);

-- The expenses / extra-income ledger. Sales are NOT mirrored here (analytics reads
-- sales for revenue and cash_movements for everything else) to avoid double counting.
-- amount is always positive; `kind` gives the direction.
CREATE TABLE IF NOT EXISTS cash_movements (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  kind        text NOT NULL CHECK (kind IN ('expense','income','adjustment')),
  amount      double precision NOT NULL,
  method      text NOT NULL DEFAULT 'cash',
  category    text NOT NULL DEFAULT '',
  note        text NOT NULL DEFAULT '',
  created_by  text NOT NULL DEFAULT 'dashboard',
  sold_at     bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  created_at  bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE INDEX IF NOT EXISTS idx_cash_movements_business_day ON cash_movements(business_id, sold_at);
