-- Backup ledger: one row per completed (or failed) backup run. Records the file,
-- its byte size, and per-table row counts, and a verified/failed status. Because
-- size_bytes and row_counts are recorded from what was actually written, a backup
-- can never claim success on an empty file — the honest-backup requirement.
CREATE TABLE IF NOT EXISTS backups (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path        text NOT NULL,
  size_bytes  bigint NOT NULL DEFAULT 0,
  row_counts  jsonb NOT NULL DEFAULT '{}'::jsonb,
  total_rows  bigint NOT NULL DEFAULT 0,
  status      text NOT NULL DEFAULT 'verified' CHECK (status IN ('verified','failed')),
  error       text,
  created_at  bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE INDEX IF NOT EXISTS idx_backups_created ON backups(created_at DESC);
