-- Inventory history + supplier receipts + the daily cash session.
-- Until now products.stock was a bare mutable integer: six code paths wrote it
-- and none of them left a trace, so "¿de dónde salió este stock?" had no answer.
-- stock_movements becomes the append-only truth of every stock change and
-- products.stock the running cache of it. stock_entries records receiving
-- merchandise (with cost, so margins stop being guesswork).
-- cash_sessions adds the missing "inicio de caja": the day's cash used to assume
-- an opening float of zero, making yesterday's carry-over invisible.

-- Every stock change, ever. Two axes on purpose:
--   kind   = what happened (a sale, a recepción, a hand count…)
--   origin = who did it (the shopkeeper, the POS, the AI, an import)
-- so "lo que hice yo" vs "lo que hizo la IA" is one WHERE clause.
-- product_id SET NULL + product_name snapshot: deleting a product must not erase
-- its history (same contract as sale_items).
-- qty_delta is signed and double precision even though products.stock is an
-- integer, so the history stays truthful even if the cache rounds.
CREATE TABLE IF NOT EXISTS stock_movements (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id  bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  product_id   bigint REFERENCES products(id) ON DELETE SET NULL,
  product_name text NOT NULL DEFAULT '',
  kind         text NOT NULL CHECK (kind IN ('entry','sale','void','adjustment','count','import')),
  origin       text NOT NULL DEFAULT 'dashboard' CHECK (origin IN ('dashboard','pos','ai','import','system')),
  qty_delta    double precision NOT NULL CHECK (qty_delta <> 0),
  stock_after  double precision,
  unit_cost    double precision,
  ref_type     text NOT NULL DEFAULT 'manual' CHECK (ref_type IN ('manual','sale','stock_entry','import','product')),
  ref_id       bigint,
  note         text NOT NULL DEFAULT '',
  created_by   text NOT NULL DEFAULT 'dashboard',
  moved_at     bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  created_at   bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE INDEX IF NOT EXISTS idx_stock_movements_business_day ON stock_movements(business_id, moved_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_movements_product ON stock_movements(product_id, moved_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_movements_ref ON stock_movements(business_id, ref_type, ref_id);

-- Receiving merchandise ("recepción"). Header + lines, mirroring sales/sale_items:
-- one recepción covers several products under one proveedor, and needs a single
-- id to hang the optional cash expense and the void off.
-- cash_movement_id links the gasto posted to Caja when post_expense is on, so
-- voiding the entry can find it again (SET NULL, never deleted — it's a ledger).
CREATE TABLE IF NOT EXISTS stock_entries (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id      bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  supplier         text NOT NULL DEFAULT '',
  note             text NOT NULL DEFAULT '',
  status           text NOT NULL DEFAULT 'applied' CHECK (status IN ('draft','applied','void')),
  total            double precision NOT NULL DEFAULT 0,
  currency         text NOT NULL DEFAULT 'PEN',
  post_expense     integer NOT NULL DEFAULT 0,
  cash_movement_id bigint REFERENCES cash_movements(id) ON DELETE SET NULL,
  created_by       text NOT NULL DEFAULT 'dashboard',
  received_at      bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  created_at       bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE INDEX IF NOT EXISTS idx_stock_entries_business_day ON stock_entries(business_id, received_at DESC);

CREATE TABLE IF NOT EXISTS stock_entry_items (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id   bigint NOT NULL REFERENCES stock_entries(id) ON DELETE CASCADE,
  product_id bigint REFERENCES products(id) ON DELETE SET NULL,
  name       text NOT NULL,
  qty        double precision NOT NULL CHECK (qty > 0),
  unit_cost  double precision NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
  line_total double precision NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_stock_entry_items_entry ON stock_entry_items(entry_id);
CREATE INDEX IF NOT EXISTS idx_stock_entry_items_product ON stock_entry_items(product_id);

-- The cash day: apertura ("con cuánto se inicia en efectivo") and cierre con conteo.
-- Keyed to a LOCAL calendar day, not a shift, because dayExpr/getCashPosition/
-- composeDigest and /api/sales?day= are all day-scoped.
-- expected_closing and difference are SNAPSHOTS taken at close time: a sale
-- recorded after the cierre must never rewrite yesterday's descuadre.
CREATE TABLE IF NOT EXISTS cash_sessions (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id      bigint NOT NULL DEFAULT 1 REFERENCES businesses(id),
  day              text NOT NULL CHECK (day ~ '^\d{4}-\d{2}-\d{2}$'),
  status           text NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),
  opening_amount   double precision NOT NULL DEFAULT 0 CHECK (opening_amount >= 0),
  opened_at        bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  opened_by        text NOT NULL DEFAULT 'dashboard',
  closing_counted  double precision,
  expected_closing double precision,
  difference       double precision,
  closed_at        bigint,
  closed_by        text,
  note             text NOT NULL DEFAULT '',
  created_at       bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_cash_sessions_business_day ON cash_sessions(business_id, day);
